### ISSUE TITLE
How to adjust the contrast for output image 

### ISSUE THREAD

**Issue by Donghai001** [PyLorentz/PyLorentz#67]
Dear developers,

Thank you for developing this excellent software package. I have a query concerning the image contrast, specifically the background brightness. Occasionally, I've noticed that the output image has a rather dark background. I'm wondering if there are any parameters or methods available within the software to adjust this contrast. Your assistance with this matter is greatly appreciated.

Best,
Donghai

**Comment by Art-MC** [comment]
Hi Donghai, there are a couple of things that can cause this depending on exactly what you're seeing. There are two main things that come to mind given your description: 

1) The total intensity of the object wave is too low due to amplitude contrast from the sample. This is can occur if the sample is too thick or if the chosen extinction distance is too small. Basically it means that the amplitude of the electron wave is smaller than it should be, which pushes the background value closer to 0, and effectively shifts the contrast range down. 

The solution to this is to first increase the sample extinction distance, `"sample_xip0"` in the `sample_params` dictionary. You can just try setting it to an arbitrarily large value like 1e3 and that will hopefully fix it. If you're simulating a sample with non-uniform topography, you can also mess about with the mean inner potential `v0`, as that can make a difference as well due to the induced electrostatic phase shift, but if the sample is uniform topography then make sure `v0 = 0`.  

2) The other potential reason for the dark background is simply due to the scaling of the displayed image. This can happen if you are using a large defocus value and or have a spin texture that heavily converges the electron beam (such as a vortex or even a Neel skyrmion sometimes). Where the beam diverges (dark regions of the image) there is a minimum intensity of 0 electrons, i.e. an intensity of 0. However there is no real limit to the converging beam intensity, or the intensity of the bright regions. This means that for an image with a defocus of say 100 um, the intensity range of the simulated image will be 0.5 to 1.5. For a defocus of 1 mm the intensity range could be 0.2 to 1.8, but then for 10 mm it could be 0.05 to 2.5. The background intensity (away from the spin texture) of the 10 mm image would be 1.0 just like in the 100 um image, but the middle of the intensity scale would be 1.25. Therefore if we view the 10 mm image with the full color range, the background would appear darker. 

The fix for this is normally just displaying the image with a fixed scale range. Setting vmin and vmax will keep the background color the same regardless of defocus value.

**Comment by Donghai001** [comment]
I deeply appreciate the thoroughness of your reply. Your detailed response was most helpful, and I've learned a great deal from it. Thank you for sharing your insights!  :)

**Comment by Art-MC** [comment]
Happy to help, you can also reach out via email if you have other questions!
